#!/bin/sh
cutargs="$(printf "%s\n" "$1" | tr '%' '\n' | tail -n+2 | grep '^[sukdPpqfU]' | sed 's/^\(.\).*/-\1/g')"
count="$(echo $cutargs | tr '-' '\n' | grep -c .)"
printfargs="$(printf "%s\n" "$1" | sed 's/%[sukdPpqfU]/%s/g')"
cuturl "$cutargs" | tr '\n' '\0' | xargs -n $count -0 printf "$printfargs"
