#!/bin/bash
#uristart.log /should/ already be uniq'd because of uristart's code now, but might as well not rely on it.
exec copy_start_nevermind.sh "$(cat <(printf "%s\n" $(xclip -o | head -n1)) <(cat ~/.cache/uristart.log | sort | uniq) | dmenu -l 10 -p urilaunch\> | cut '-d ' -f1)"
