#!/bin/bash
#uristart.log /should/ already be uniq'd because of uristart's code now, but might as well not rely on it.
uristart $(cat <(printf "%s\n" $(xclip -o | head -n1)) <(cat ~/.cache/uristart.log | sort | uniq) | dmenu -p url\> | cut '-d ' -f1)
